// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using integralApi.Data;

#nullable disable

namespace integralApi.Data.Migrations
{
    [DbContext(typeof(IntegralContext))]
    partial class IntegralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("integralApi.Data.Eq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Answer")
                        .HasColumnType("double precision");

                    b.Property<string>("Equation")
                        .HasColumnType("text");

                    b.Property<string>("FirstNumber")
                        .HasColumnType("text");

                    b.Property<string>("LastNumber")
                        .HasColumnType("text");

                    b.Property<string>("Variable")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Expressions");
                });
#pragma warning restore 612, 618
        }
    }
}
